/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package router.demo;
import com.graphhopper.*;
import com.graphhopper.routing.util.*;
import com.graphhopper.util.*;
import com.graphhopper.reader.osm.GraphHopperOSM;
import com.graphhopper.util.*;

import java.util.List; 
import java.util.Map;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;

public class App {

    public static void main(String[] args) {

         
        //======================= Route Planning =====================================
        GraphHopper hopper = new GraphHopperOSM().forServer();

        hopper.setDataReaderFile("src/main/resources/bretagne-latest.osm.pbf")
        .setGraphHopperLocation("temp")
        .setEncodingManager(new EncodingManager("foot"))
        .setCHEnabled(false);

        // Load OSM File
        System.out.println("Loading OSM file ...");
        hopper.importOrLoad();

        // Configuring route
        // simple configuration of the request object, see the GraphHopperServlet classes for more possibilities.
        GHRequest req = new GHRequest(48.4084, -4.4982, 48.3748, -4.5976).
        setVehicle("foot").
        setAlgorithm(Parameters.Algorithms.ALT_ROUTE);
        req.getHints().put(Parameters.Algorithms.AltRoute.MAX_PATHS, "5");
        GHResponse rsp = hopper.route(req);

        // first check for errors
        if(rsp.hasErrors()) {
            // handle them!
            // rsp.getErrors()
        }

        PathWrapper path = rsp.getBest();
        List<PathWrapper> paths =rsp.getAll();
        PointList pointList = path.getPoints();
        double distance = path.getDistance();
        long timeInMs = path.getTime();
        
        InstructionList il = path.getInstructions();
   
        // or get the json
        List<Map<String, Object>> iList = il.createJson();
        
        System.out.println("Everything worked !");
        System.out.println("==============================================================================");
        Gson gson = new GsonBuilder().setPrettyPrinting().create();
        String prettyJsonString = gson.toJson(iList);
        //System.out.println(prettyJsonString);
        System.out.println("==============================================================================");
        System.out.println(paths);
        System.out.println("==============================================================================");
        System.out.println(prettyJsonString);
    }
}
